#!/bin/sh
set -eu

case "$*" in
  "-y --setopt=install_weak_deps=False install ca-certificates curl gnupg2"|\
  "-q --disablerepo=* --enablerepo=docker-ce-stable makecache"|\
  "-y --setopt=install_weak_deps=False install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin")
    exit 0
    ;;
esac

exit 64
