"""Security primitives used by the AdoJapan Restream backend.

The module deliberately contains no application or database state.  It provides
small, auditable wrappers around well-reviewed primitives and leaves persistence
and key lifecycle decisions to the caller.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets
from typing import Final

from argon2 import PasswordHasher, Type
from argon2.exceptions import InvalidHashError, VerificationError, VerifyMismatchError
from cryptography.fernet import Fernet, InvalidToken

DEFAULT_TOKEN_BYTES: Final = 32
"""Default entropy for opaque tokens (256 bits before encoding)."""


class InvalidMasterKeyError(ValueError):
    """Raised when a configured master key is not a valid Fernet key."""


class SecretDecryptionError(ValueError):
    """Raised when an encrypted secret cannot be authenticated or decrypted."""


# Explicit parameters make the resource cost reviewable and ensure Argon2id is
# retained even if argon2-cffi changes its defaults in a future release.
_PASSWORD_HASHER = PasswordHasher(
    time_cost=3,
    memory_cost=65_536,
    parallelism=1,
    hash_len=32,
    salt_len=16,
    type=Type.ID,
)


def _require_text(value: str, name: str, *, allow_empty: bool = False) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{name} must be a string")
    if not allow_empty and not value:
        raise ValueError(f"{name} must not be empty")
    return value


def _token_urlsafe(nbytes: int) -> str:
    if isinstance(nbytes, bool) or not isinstance(nbytes, int):
        raise TypeError("nbytes must be an integer")
    if nbytes < 16:
        raise ValueError("nbytes must provide at least 128 bits of entropy")
    return secrets.token_urlsafe(nbytes)


def hash_password(password: str) -> str:
    """Return an Argon2id encoded hash for ``password``.

    A fresh random salt is generated by argon2-cffi for every call.  The result
    is safe to persist; the original password must never be stored.
    """

    return _PASSWORD_HASHER.hash(_require_text(password, "password"))


def verify_password(password: str, encoded_hash: str) -> bool:
    """Safely compare ``password`` with an Argon2 encoded hash.

    Invalid or non-Argon2 hashes are treated like a password mismatch so callers
    do not need to expose parsing details through an authentication endpoint.
    """

    _require_text(password, "password", allow_empty=True)
    _require_text(encoded_hash, "encoded_hash", allow_empty=True)
    if not encoded_hash:
        return False
    try:
        return bool(_PASSWORD_HASHER.verify(encoded_hash, password))
    except (VerifyMismatchError, VerificationError, InvalidHashError):
        return False


def password_hash_needs_rehash(encoded_hash: str) -> bool:
    """Return whether ``encoded_hash`` should be upgraded to current settings."""

    _require_text(encoded_hash, "encoded_hash")
    try:
        return _PASSWORD_HASHER.check_needs_rehash(encoded_hash)
    except (VerificationError, InvalidHashError):
        return True


def generate_ingest_key(nbytes: int = DEFAULT_TOKEN_BYTES) -> str:
    """Generate a URL-safe, cryptographically random RTMP ingest key."""

    return _token_urlsafe(nbytes)


def rotate_ingest_key(current_key: str | None = None, nbytes: int = DEFAULT_TOKEN_BYTES) -> str:
    """Generate a replacement ingest key that differs from ``current_key``.

    Rotation is intentionally stateless.  Persisting the new key and revoking
    the previous one must happen atomically in the application's data layer.
    """

    if current_key is not None:
        _require_text(current_key, "current_key", allow_empty=True)
    replacement = generate_ingest_key(nbytes)
    while current_key is not None and secrets.compare_digest(replacement, current_key):
        replacement = generate_ingest_key(nbytes)
    return replacement


# These aliases mirror the terminology used by the UI and keep call sites clear.
generate_stream_key = generate_ingest_key
rotate_stream_key = rotate_ingest_key


def generate_master_key() -> str:
    """Generate a Fernet master key for one-time configuration.

    This helper must be invoked explicitly during initialization; applications
    must not call it automatically at startup because losing the configured key
    makes every previously encrypted destination secret unrecoverable.
    """

    return Fernet.generate_key().decode("ascii")


def _build_fernet(master_key: str | bytes) -> Fernet:
    if not isinstance(master_key, (str, bytes)):
        raise TypeError("master_key must be a string or bytes")
    if not master_key:
        raise InvalidMasterKeyError("master_key must not be empty")
    try:
        key_bytes = master_key.encode("ascii") if isinstance(master_key, str) else master_key
        return Fernet(key_bytes)
    except (TypeError, ValueError, UnicodeEncodeError) as exc:
        raise InvalidMasterKeyError(
            "master_key must be a URL-safe base64 encoded 32-byte Fernet key"
        ) from exc


def encrypt_destination_key(destination_key: str, master_key: str | bytes) -> str:
    """Encrypt and authenticate a destination stream key using Fernet."""

    plaintext = _require_text(destination_key, "destination_key").encode("utf-8")
    return _build_fernet(master_key).encrypt(plaintext).decode("ascii")


def decrypt_destination_key(encrypted_key: str | bytes, master_key: str | bytes) -> str:
    """Authenticate and decrypt a destination stream key.

    ``SecretDecryptionError`` intentionally does not distinguish a wrong master
    key from corrupted ciphertext, avoiding an unnecessary decryption oracle.
    """

    if not isinstance(encrypted_key, (str, bytes)):
        raise TypeError("encrypted_key must be a string or bytes")
    if not encrypted_key:
        raise SecretDecryptionError("encrypted destination key must not be empty")
    token = encrypted_key.encode("ascii") if isinstance(encrypted_key, str) else encrypted_key
    try:
        plaintext = _build_fernet(master_key).decrypt(token)
        return plaintext.decode("utf-8")
    except (InvalidToken, UnicodeDecodeError, UnicodeEncodeError) as exc:
        raise SecretDecryptionError("encrypted destination key is invalid") from exc


def generate_session_id(nbytes: int = DEFAULT_TOKEN_BYTES) -> str:
    """Generate an opaque session identifier suitable for a secure cookie."""

    return _token_urlsafe(nbytes)


def generate_csrf_token(nbytes: int = DEFAULT_TOKEN_BYTES) -> str:
    """Generate an unpredictable synchronizer token for CSRF protection."""

    return _token_urlsafe(nbytes)


def verify_csrf_token(expected: str | None, provided: str | None) -> bool:
    """Compare CSRF tokens in constant time, returning ``False`` for missing values."""

    if not isinstance(expected, str) or not isinstance(provided, str):
        return False
    if not expected or not provided:
        return False
    return secrets.compare_digest(expected, provided)


def digest_opaque_token(token: str) -> str:
    """Return a deterministic SHA-256 digest for server-side token lookup.

    Storing this digest instead of a session or ingest token limits the impact of
    a read-only database disclosure.  The original high-entropy token remains in
    the client's cookie or streaming software.
    """

    value = _require_text(token, "token").encode("utf-8")
    return hashlib.sha256(value).hexdigest()


def generate_enrollment_token(nbytes: int = DEFAULT_TOKEN_BYTES) -> str:
    """Generate a one-time node enrollment token with at least 256-bit entropy."""

    return _token_urlsafe(nbytes)


def generate_node_token(node_id: str, nbytes: int = DEFAULT_TOKEN_BYTES) -> str:
    """Generate a routable permanent node token without weakening its secret part."""

    identifier = _require_text(node_id, "node_id")
    if "_" in identifier:
        raise ValueError("node_id must not contain underscores")
    return f"node_{identifier}_{_token_urlsafe(nbytes)}"


def verify_opaque_token_digest(token: str | None, expected_digest: str | None) -> bool:
    """Authenticate a high-entropy opaque token with a constant-time digest comparison."""

    if not isinstance(token, str) or not isinstance(expected_digest, str):
        return False
    if not token or len(expected_digest) != 64:
        return False
    provided_digest = hashlib.sha256(token.encode("utf-8")).hexdigest()
    return hmac.compare_digest(provided_digest, expected_digest)


__all__ = [
    "DEFAULT_TOKEN_BYTES",
    "InvalidMasterKeyError",
    "SecretDecryptionError",
    "decrypt_destination_key",
    "digest_opaque_token",
    "encrypt_destination_key",
    "generate_csrf_token",
    "generate_enrollment_token",
    "generate_ingest_key",
    "generate_master_key",
    "generate_node_token",
    "generate_session_id",
    "generate_stream_key",
    "hash_password",
    "password_hash_needs_rehash",
    "rotate_ingest_key",
    "rotate_stream_key",
    "verify_csrf_token",
    "verify_opaque_token_digest",
    "verify_password",
]
